@startuml

class キャラクター{
    名前
    HP

    + 戦う()
    + 逃げる()
}

class 魔法使い{
    + 眠る()
    + 魔法()
}

class 勇者{
    + 眠る()
    + 座る()
}

class スライム{
    + 飲み込む()
}

キャラクター <|-- 魔法使い
キャラクター <|-- 勇者
キャラクター <|-- スライム

@enduml